# Config
nimbus:
  host: localhost
  port: 8772

redis:
  host: localhost
  port: 6379

predictor:
  host: localhost
  port: 5000

storm:
  deploy:
    duration: 22
    script: "serverlessApp.sh"
    dataset: "dns"
    analyze: true
  adaptive:
    time_window_size: 1
    benchmark_samples: 60
    analyze_samples: 15
    predictive_model: multi
    prediction_samples: 30
    prediction_number: 15
    limit_replicas: 100
  rest_metric:
    port: 3000
  csv: "stats/"

gcp:
  auth_credential: "~/.config/gcloud/application_default_credentials.json"
  project: "sps-storm"
