# Config
nimbus:
  host: localhost
  port: 8772

redis:
  host: localhost
  port: 6379

storm:
  deploy:
    duration: 22
    script: "App1.sh"
    analyze: true
  adaptive:
    time_window_size: 5
    benchmark_samples: 12
    prediction_samples: 6
    prediction_input: lineal
    input_samples: 12
    input_predict: 6
    limit_replicas: 100
  csv: "stats/"
