# Config
nimbus:
  host: localhost
  port: 8772

redis:
  host: localhost
  port: 6379

predictor:
  host: localhost
  port: 5000

storm:
  deploy:
    duration: 22
    script: "App1.sh"
    analyze: true
  adaptive:
    time_window_size: 5
    benchmark_samples: 12
    analyze_samples: 6
    predictive_model: lineal
    prediction_samples: 12
    prediction_number: 6
    limit_replicas: 100
  csv: "stats/"
