# Config
nimbus:
  host: localhost
  port: 8772

redis:
  host: localhost
  port: 6379

storm:
  deploy:
    duration: 65
    script: "app-2.sh"
    analyze: true
  adaptive:
    time_window_size: 5
    logical:
      benchmark:
        number_samples: 12
      reactive:
        number_samples: 5
        upper_limit: 0.7
        lower_limit: 0.3
        number_replicas: 1
      predictive:
        number_samples: 120
        number_replicas: 10
      metric:
        throughput_weight: 0.45
        latency_weight: 0.1
        latency_limit: 0.5
        queue_weight: 0.45
  csv: "stats/"
