# Config
nimbus:
  host: localhost
  port: 8772

redis:
  host: localhost
  port: 6379

predictor:
  host: localhost
  port: 5000

storm:
  deploy:
    duration: 22
    script: "serverlessApp.sh"
    analyze: false
  adaptive:
    time_window_size: 5
    benchmark_samples: 12
    analyze_samples: 6
    predictive_model: basic
    prediction_samples: 12
    prediction_number: 6
    limit_replicas: 100
  rest_metric:
    port: 3000
  csv: "stats/"

gcp:
  auth_credential: "~/.config/gcloud/application_default_credentials.json"
  project: "sps-storm"
